### PR TITLE
Proposing changes to support scheduling (svn add/delete) in the workspace

### PR DESCRIPTION
**Pull request by patricematignon**
Also, support for lastCommittedDate / lastCommittedAuthor in SvnData

### CODE REVIEW

**Comment by patricematignon** [comment]
I can't reproduce that failing test locally. Any advise or comments ?

**Comment by martoe** [comment]
No idea, it also works for me. I have to look into the Travis-CI config... please ignore these errors for now

About your PR:
1. Thanks! :-)
2. I think I understand your usage example (haven't thought of this before), but I would prefer splitting up the `SvnWCFiles` task into special-purpose tasks, e.g. `SvnAddFiles` and `SvnDeleteFiles` (or even `SvnAdd` and `SvnDelete`), so that every type of task has its sole purpose.
We could then provide an API similar to the Gradle core tasks (like [Delete](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Delete.html), or even [Copy](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html) for a future release).
What do you think?

**Comment by patricematignon** [comment]
Hello Martin,

I thought about breaking up the task, but I thought it is more convenient if you can add / remove in the same task. Otherwise you'd have to daisy-chain your tasks for add/delete.
I was even thinking of adding the ability to do an svn revert (since it also applies to the WC files).

You are welcome to overrule of course.
(I won't be able to get back to this for a couple weeks though.)

**Comment by martoe** [comment]
Sorry to hear that you don't have more time for this... I will use a feature branch for now, because at least I have to write some basic unittests before merging to the mainline.

Cheers,
Martin

**Pull request merged**
